//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoftManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программа.
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор приложения.
        /// </summary>
        internal static string ApplicationID {
            get {
                return ResourceManager.GetString("ApplicationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программа не найдена.
        /// </summary>
        internal static string ApplicationNotFound {
            get {
                return ResourceManager.GetString("ApplicationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово!.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя компьютера.
        /// </summary>
        internal static string ComputerName {
            get {
                return ResourceManager.GetString("ComputerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копирование файлов....
        /// </summary>
        internal static string CopyFiles {
            get {
                return ResourceManager.GetString("CopyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка ввода данных!.
        /// </summary>
        internal static string DataEntryError {
            get {
                return ResourceManager.GetString("DataEntryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата Установки.
        /// </summary>
        internal static string DateOfInstalation {
            get {
                return ResourceManager.GetString("DateOfInstalation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление .
        /// </summary>
        internal static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получение списка установленных программ.
        /// </summary>
        internal static string GettingListOfInstalledPrograms {
            get {
                return ResourceManager.GetString("GettingListOfInstalledPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справка.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Узел недоступен.
        /// </summary>
        internal static string HostNotAvailable {
            get {
                return ResourceManager.GetString("HostNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установка....
        /// </summary>
        internal static string Instalation {
            get {
                return ResourceManager.GetString("Instalation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результаты установки.
        /// </summary>
        internal static string InstalationResults {
            get {
                return ResourceManager.GetString("InstalationResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояние установки.
        /// </summary>
        internal static string InstalationStatus {
            get {
                return ResourceManager.GetString("InstalationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать имя компьютера!.
        /// </summary>
        internal static string MustSpecifyComputerName {
            get {
                return ResourceManager.GetString("MustSpecifyComputerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать дистрибутив!.
        /// </summary>
        internal static string MustSpecifyDistributive {
            get {
                return ResourceManager.GetString("MustSpecifyDistributive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояние процесса.
        /// </summary>
        internal static string ProcessStatus {
            get {
                return ResourceManager.GetString("ProcessStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoftManager.
        /// </summary>
        internal static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результаты удаления.
        /// </summary>
        internal static string RemovingResults {
            get {
                return ResourceManager.GetString("RemovingResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сканирование.
        /// </summary>
        internal static string Scaning {
            get {
                return ResourceManager.GetString("Scaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сканирование завершено.
        /// </summary>
        internal static string ScaningComplete {
            get {
                return ResourceManager.GetString("ScaningComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск программы....
        /// </summary>
        internal static string SearchingProgram {
            get {
                return ResourceManager.GetString("SearchingProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установка программ.
        /// </summary>
        internal static string SoftwareInstalation {
            get {
                return ResourceManager.GetString("SoftwareInstalation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список программного обеспечения на компьютере.
        /// </summary>
        internal static string SoftwareListOnComputer {
            get {
                return ResourceManager.GetString("SoftwareListOnComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление программ.
        /// </summary>
        internal static string SowtwareRemoving {
            get {
                return ResourceManager.GetString("SowtwareRemoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SystemInstallIcon {
            get {
                object obj = ResourceManager.GetObject("SystemInstallIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SystemUninstallIcon {
            get {
                object obj = ResourceManager.GetObject("SystemUninstallIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидание.
        /// </summary>
        internal static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
    }
}
